web: bin/start-nginx


**2. `config/nginx.conf.erb`**
This config is compatible with `bin/start-nginx`.

http://googleusercontent.com/immersive_entry_chip/0

**3. `package.json`** (Already correct, just confirming)

http://googleusercontent.com/immersive_entry_chip/1

### **Deployment Steps to Fix the Crash**

1.  **Update your files** locally with the code above.
2.  **Commit changes:**
    ```bash
    git add .
    git commit -m "Fix Procfile and NGINX config for Heroku"
    3.  **Push to Heroku:**
    ```bash
    git push heroku main
    
This should resolve the `No such file or directory` error because `bin/start-nginx` is the standard script generated by the buildpack during the build process.
